name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run container with GPU config
      run: docker-compose --env-file configs/gpu-conda.env up --build -d

    - name: Wait for container to be healthy (optional, but good practice)
      run: sleep 10 # Give container some time to start up

    - name: Check GPU availability inside container
      run: docker-compose exec app python -c "import torch; print(torch.cuda.is_available())"
